### PR TITLE
418 Test

### PR DESCRIPTION
**Pull request by ssunday**
A test to check if the server correctly implements the 418 code on the
appropriate route. The 418 code is a special code with many nuances. Its addition and implementation can add a special something to a server.

### CODE REVIEW

**Comment by KevinLiddle** [comment]
I think google might be a bit wrong on this. I believe 418 is meant to be an error code when someone requests `coffee` from server that is, in fact, a teapot.

**Comment by ssunday** [comment]
Google might be a bit wrong on this, but when has right or wrong _really_ played that big a factor in style and design? When all the other cool websites are having 418 codes and teapots showing up wherever and whenever, do you want to be the one with a lame server that _doesn't_ have a teapot route? 

I don’t.

**Comment by KevinLiddle** [comment]
I appreciate your stance on the pleasures of conformity and the importance of trends, but I think we can be _better_ than google and everyone else in this respect by doing things _right_.

To be clear, I would like to advocate for a route that returns a 418, but that the route name should be `coffee`, so as to stick to the intended meaning of the 418 error code, where a server that is a teapot cannot give you coffee. (I would think a `tea` route would return `200 OK`, or something else successful).

**Comment by ssunday** [comment]
Ah. I see your point and I have corrected the test. Now it tests the `coffee` route for a 418 code and a `tea` route for a 200 code. I think that is an improvement.

**Comment by KevinLiddle** [comment]
bitmoji

**Pull request merged**
