### PR TITLE
End the tyranny of RubySlim

### PR DESCRIPTION
**Pull request by paytonrules**
This ports all the rubyslim fixtures over to Java. Patrick and I tested this against a Sinatra server and Dave Torre's server, and are all green.

### CODE REVIEW

**Comment by paytonrules** [comment]
Hey @patrickgombert I've rebased. However I no longer have our friend the sinatra. Well I do but it's at home.  

You got anything we could use to verify this?

**Comment by patrickgombert** [comment]
@paytonrules IIRC https://github.com/davetorre/cobspecpasser was good to go

**Comment by paytonrules** [comment]
Bah! Dave Torre's doesn't start. But we did find an issue running against jake nations server.

**Comment by dcmoore** [comment]
Did those recent changes fix the issues with Jake's server? Is this good to merge?

**Comment by paytonrules** [comment]
Uku has a couple changes I haven't looked at yet.

Jake's server had a couple real issues - but I'm not on a review board
tomorrow so hopefully (crosses fingers) we can finally get this in.

**Comment by dcmoore** [comment]
:neckbeard: :+1:

**Comment by sl4m** [comment]
@heruku ^^

**Comment by heruku** [comment]
With my latest commit, this fork works fully with my own server. I'll try it against @felipesere's implementation today.

**Comment by paytonrules** [comment]
I did a review of heruku's changes and they look good to me. He's gotten it passing on @felipesere and his own server, so I think we're ready to go.

**Pull request merged**
